In [2]:
import numpy as np
import pandas as pd 

cu = pd.read_csv("D:/Files/2019 Spring/High P Com/Project/trace_201708/trace_201708/container_usage.csv")
cu.head()

ts  instance_id  cpu_util  mem_util  disk_util  load1  load5  load15  \
0  42900          106     42.84     65.52      17.14   3.14   3.40    3.66   
1  42600          107      3.30     24.00       5.20   0.54   0.38    0.30   
2  42300          108      3.14     25.60      10.60   0.08   0.14    0.20   
3  42000          109      3.82     42.00      13.90   0.10   0.16    0.20   
4  41700          110      5.82     24.90       7.40   0.74   0.62    0.60   

    avg_cpi  avg_mpki   max_cpi   max_mpki  
0  0.064628  0.034337  0.726102   0.457576  
1  0.155430  0.550153  2.211467  12.187318  
2  0.199342  0.294852  2.633724   3.997216  
3  0.238470  0.292426  2.203077   2.942878  
4  0.136100  0.161496  1.622428   2.469633

In [8]:
cu_cpu_util = np.sort(cu.cpu_util)
cu_cpu_util

array([0.3       , 0.30000001, 0.32000001, ...,        nan,        nan,
              nan])

In [10]:
cu_instance_id = np.sort(cu.instance_id)
cu_instance_id

array([    1,     1,     1, ..., 11275, 11275, 11275], dtype=int64)

In [15]:
cu_ts = np.sort(cu.ts)
cu_ts

array([39600, 39600, 39600, ..., 82500, 82500, 82500], dtype=int64)

In [18]:
instance_cpu_util_avg = {}
for i_id in cu_instance_id:
    instance_cpu_util_avg[i_id] = sum(cu[cu.instance_id == i_id].cpu_util) 
instance_cpu_util_avg 

KeyboardInterrupt: 

In [19]:
import seaborn as sns

pivot = cu.pivot(index=cu_instance_id, columns=cu.ts, values=cu.cpu_util)
ax = sns.heatmap(pivot,annot=True)
plt.show()

print (pivot)

KeyError: '[  106   107   108 ... 10177 10178 10179] not in index'